// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWjc5bRnl22OVUdMkUywOl_yDmfUvae3M',
    appId: '1:622340299498:web:3a4f1e00f239467b189593',
    messagingSenderId: '622340299498',
    projectId: 'star-shop-29072003',
    authDomain: 'star-shop-29072003.firebaseapp.com',
    storageBucket: 'star-shop-29072003.appspot.com',
    measurementId: 'G-Z0DGQZ2M2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcxyF6MtgpPBFKA6yBOR71xU-Um1REs9o',
    appId: '1:622340299498:android:248b92b92038cc70189593',
    messagingSenderId: '622340299498',
    projectId: 'star-shop-29072003',
    storageBucket: 'star-shop-29072003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkXDB7W41s6Ef6oCJL7kGN0iDKpjPKiTM',
    appId: '1:622340299498:ios:72ef97d3461b94a2189593',
    messagingSenderId: '622340299498',
    projectId: 'star-shop-29072003',
    storageBucket: 'star-shop-29072003.appspot.com',
    iosBundleId: 'com.example.starShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkXDB7W41s6Ef6oCJL7kGN0iDKpjPKiTM',
    appId: '1:622340299498:ios:72ef97d3461b94a2189593',
    messagingSenderId: '622340299498',
    projectId: 'star-shop-29072003',
    storageBucket: 'star-shop-29072003.appspot.com',
    iosBundleId: 'com.example.starShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWjc5bRnl22OVUdMkUywOl_yDmfUvae3M',
    appId: '1:622340299498:web:bf7898c857311928189593',
    messagingSenderId: '622340299498',
    projectId: 'star-shop-29072003',
    authDomain: 'star-shop-29072003.firebaseapp.com',
    storageBucket: 'star-shop-29072003.appspot.com',
    measurementId: 'G-VBM0884P0F',
  );
}
